define([], function () {
  return {
    BasicGroupName: 'Settings',
    FieldLabelApiKey: 'Optional api-key for Azure OpenAI (for troubleshooting, not for Production)',
    FieldLabelAppId: 'Client ID: create a user_impersonation app with name=openaiwp',
    FieldLabelEndpointBaseUrlForChatHistory: 'Base URL for Chat WebApi (APIM API or full)',
    FieldLabelEndpointBaseUrlForOpenAi: 'Base URL for GPT endpoint (APIM API or full)',
    FieldLabelEndpointBaseUrlForOpenAi4: 'Base URL for GPT4 endpoint (APIM API or full)',
    FieldLabelLanguageModels: 'Language models',
    FieldLabelLocale: 'Locale for dates (default is fi-FI)',
    FieldLabelSharing: 'Enable sharing',
    FieldLabelStreaming: 'Enable streaming',
    FieldLabelFullScreen: 'Enable full screen mode',
    FieldLabelFunctions: 'Enable integrations',
    FieldLabelHighlight: 'Code highlighting',
    FieldLabelHighlightStyles: 'Show highlighting styles',
    FieldLabelDefaultStyle: 'Default style',
    FieldLabelSharePointListUrl: 'SharePoint list URL (leave it empty for default URL)',
    FieldLabelStorageType: 'Storage type for chat history',
    FieldLabelStorageTypeDatabase: 'Database',
    FieldLabelStorageTypeLocalStorage: 'Local storage',
    FieldLabelStorageTypeSharePoint: 'SharePoint list',
    FieldLabelDemoOnly: '(demo only)',
    FieldLabelPromptAtBottom: 'Show prompt area at bottom',
    FieldLabelUnlimitedHistoryLength: 'Unlimited chat history length (AI-responses in long chats may be less accurate)',

    PlaceholderDescription: 'Please configure this web part.',
    PlaceholderText: 'Configure your web part',

    TextAllResults: 'All results',
    TextAuthenticationError: 'Authentication error (refer to console messages for details)',
    TextCancel: 'Cancel',
    TextCharacters: 'characters',
    TextChat: 'ChatGPT',
    TextClose: 'Close',
    TextCodeStyle: 'Code style',
    TextCollapse: 'Collapse',
    TextCommands: 'commands',
    TextConfigure: 'Configure',
    TextCopy: 'Copy',
    TextCreate: 'Create',
    TextCreated: 'Created',
    TextDelete: 'Delete',
    TextDeleteMessage: 'Do you want to delete',
    TextDescribeImage: 'What is in this image?',
    TextDescribeImages: 'What is in these images?',
    TextEdit: 'Edit',
    TextError: 'Error occurred',
    TextExists: 'Exists',
    TextExpand: 'Expand',
    TextFormat: 'Raw',
    TextFullScreen: 'To full screen',
    TextGpt35: 'GPT-3.5',
    TextGpt4: 'GPT-4',
    TextHideMySharedChats: 'Hide my chats',
    TextInvalidListUrl: 'Invalid list URL. Custom list with the same name already exists at the site',
    TextListCreated: 'Custom list has been created',
    TextListDoesNotExist: 'Custom list does not exist',
    TextListExists: 'Custom list already exists',
    TextListUpdated: 'Custom list has been updated',
    TextMaxContentLengthExceeded: 'Max chat history length allowed by the selected language model exceeded. Start a New chat or select another language model.',
    TextModified: 'Last modified',
    TextMoreCharactersAllowed: 'more allowed',
    TextNewChat: 'New chat',
    TextPeoplePicker: 'People Picker',
    TextPeoplePickerLoading: 'Loading',
    TextPeoplePickerNoResults: 'No results found',
    TextPeoplePickerSuggestedContacts: 'Suggested contacts',
    TextPeoplePickerSuggestedPeople: 'Suggested people',
    TextPeoplePickerSuggestionsAvailable: 'People Picker Suggestions available',
    TextRecentChats: 'My chats',
    TextRefresh: 'Refresh',
    TextRemove: 'Remove',
    TextSave: 'Save',
    TextSendMessage: 'Send a message',
    TextShare: 'Share',
    TextShared: 'Shared',
    TextShareMessage: 'Do you want to share',
    TextSharedChats: 'Shared chats',
    TextShareWith: 'Specific people to share with (if you want to limit access to this chat, max 15 persons)',
    TextSubmit: 'Submit',
    TextSummarizePdf: 'Summarise PDF content',
    TextUndeterminedError: 'Undetermined error',
    TextUnshare: 'Unshare',
    TextUnshareMessage: 'Do you want to unshare',
    TextUpdate: 'Update',
    TextUpdated: 'Updated',
    TextUpload: 'Upload',
    TextUploadFiles: 'Upload files',
    TextUploadImage: 'Upload images',
    TextUploadPdf: 'Upload PDF',
  };
});
