define([], function () {
  return {
    BasicGroupName: 'Asetukset',
    FieldLabelApiKey: 'Valinnainen api-avain Azure OpenAI:lle (vianmääritystä varten, ei tuotantoa varten)',
    FieldLabelApiKeyPlaceholder: 'Lisää, jos APIM-päätepistettä ei käytetä',
    FieldLabelAppId: 'Client ID: luo user_impersonation-sovellus nimellä=openaiwp',
    FieldLabelEndpointBaseUrlForChatHistory: 'Chat WebApin perus-URL-osoite (APIM API tai täysi)',
    FieldLabelEndpointBaseUrlForOpenAi: 'GPT-päätepisteen perus-URL-osoite (APIM API tai täysi)',
    FieldLabelEndpointBaseUrlForOpenAi4: 'GPT4-päätepisteen perus-URL-osoite (APIM API tai täysi)',
    FieldLabelBing: 'Bing-haku',
    FieldLabelBingApiKey: 'Valinnainen api-avain Bingille',
    FieldLabelBingApiKeyPlaceholder: 'Lisää, jos APIM-päätepistettä ei ole määritetty',
    FieldLabelGoogle: 'Google-haku',
    FieldLabelGoogleApiKey: 'Valinnainen avain Googlelle: key=API_AVAIN&cx=HAKUKONEEN_ID',
    FieldLabelLanguageModels: 'Kielimallit',
    FieldLabelLocale: 'Päivämäärien kielikieli (oletus on fi-FI)',
    FieldLabelSharing: 'Ota jakaminen käyttöön',
    FieldLabelStreaming: 'Ota suoratoisto käyttöön',
    FieldLabelFullScreen: 'Ota käyttöön koko näytön tila',
    FieldLabelFunctions: 'Ota integraatiot käyttöön',
    FieldLabelHighlight: 'Koodikorostus',
    FieldLabelHighlightStyles: 'Näytä korostustyylit',
    FieldLabelDefaultStyle: 'Oletustyyli',
    FieldLabelSharePointListUrl: 'SharePoint-luettelon URL-osoite (jätä se tyhjäksi oletus-URL-osoitteelle)',
    FieldLabelStorageType: 'Tallennustyyppi chattihistorialle',
    FieldLabelStorageTypeDatabase: 'Tietokanta',
    FieldLabelStorageTypeLocalStorage: 'Paikallinen varasto',
    FieldLabelStorageTypeSharePoint: 'SharePoint-luettelo',
    FieldLabelDemoOnly: '(vain demo)',
    FieldLabelPromptAtBottom: 'Näytä kehotealue alareunassa',
    FieldLabelUnlimitedHistoryLength: 'Rajoittamaton chatin historian pituus (AI-vastaukset pitkissä keskusteluissa voivat olla vähemmän tarkkoja)',

    PlaceholderDescription: 'Määritä tämä verkko-osa.',
    PlaceholderText: 'Määritä verkko-osa',

    TextAllResults: 'Kaikki tulokset',
    TextAuthenticationError: 'Todennusvirhe (katso lisätietoja konsolin viesteistä)',
    TextCancel: 'Peruuta',
    TextCharacters: 'merkit',
    TextChat: 'ChatGPT',
    TextClose: 'Sulje',
    TextCodeStyle: 'Koodityyli',
    TextCollapse: 'Tiivistä',
    TextCommands: 'komentoja',
    TextConfigure: 'Määritä',
    TextCopy: 'Kopioi',
    TextCreate: 'Luota',
    TextCreated: 'Luotu',
    TextDelete: 'Poista',
    TextDeleteMessage: 'Haluatko poistaa',
    TextDescribeImage: 'Mitä tässä kuvassa on?',
    TextDescribeImages: 'Mitä näissä kuvissa on?',
    TextEdit: 'Muokkaa',
    TextError: 'Tapahtui virhe',
    TextExists: 'On olemassa',
    TextExpand: 'Laajenna',
    TextFormat: 'Raaka',
    TextFullScreen: 'Koko näyttöön',
    TextGpt35: 'GPT-3.5',
    TextGpt4: 'GPT-4',
    TextGpt4Turbo: 'GPT-4 Turbo',
    TextHideMySharedChats: 'Piilota chattini',
    TextInvalidListUrl: 'Virheellinen luettelon URL-osoite. Muokattu luettelo samalla nimella on jo olemassa sivustolla',
    TextListCreated: 'Muokattu luettelo on luotu',
    TextListDoesNotExist: 'Mukautettua luetteloa ei ole olemassa',
    TextListExists: 'Muokattu luettelo on jo olemassa',
    TextListUpdated: 'Muokattu luettelo on päivitetty',
    TextMaxContentLengthExceeded: 'Valitun kielimallin sallima chatin historian enimmäispituus ylitetty. Lisää uusi chatti tai valitse toinen kielimalli.',
    TextModified: 'Viimeksi muokattu',
    TextMoreCharactersAllowed: 'merkkiä lisää sallittu',
    TextNewChat: 'Lisää chatti',
    TextPeoplePicker: 'Tilin valitsin',
    TextPeoplePickerLoading: 'Ladataan',
    TextPeoplePickerNoResults: 'Tuloksia ei löytynyt',
    TextPeoplePickerSuggestedContacts: 'Ehdotetut yhteystiedot',
    TextPeoplePickerSuggestedPeople: 'Ehdotetut ihmiset',
    TextPeoplePickerSuggestionsAvailable: 'Ihmisten valinnan ehdotuksia saatavilla',
    TextPreview: 'Esikatselu, ei tuotantoon',
    TextRecentChats: 'Omat chatit',
    TextRefresh: 'Päivitä',
    TextRemove: 'Poista',
    TextSave: 'Tallenna',
    TextSendMessage: 'Lähetä viesti',
    TextShare: 'Jaa',
    TextShared: 'Jaettu',
    TextShareMessage: 'Haluatko jakaa',
    TextSharedChats: 'Jaetut chatit',
    TextShareWith: 'Tietyt ihmiset, joiden kanssa jakaa (jos haluat rajoittaa pääsyä tähän keskusteluun, enintään 15 henkilöä)',
    TextStop: 'Lopeta',
    TextSubmit: 'Lähetä',
    TextSummarizePdf: 'Tee yhteenveto PDF-sisällöstä',
    TextUndeterminedError: 'Määrittämätön virhe',
    TextUnshare: 'Peruuta jakaminen',
    TextUnshareMessage: 'Haluatko peruuttaa jakamisen',
    TextUpdate: 'Päivitä',
    TextUpdated: 'Päivitetty',
    TextUpload: 'Lataa',
    TextUploadFiles: 'Lataa tiedostoja',
    TextUploadImage: 'Lataa kuvia',
    TextUpload: 'Lataa PDF',
  };
});
