define([], function () {
  return {
    BasicGroupName: 'Innstillinger',
    FieldLabelApiKey: 'Valgfri api-nøkkel for Azure OpenAI (for feilsøking, ikke for produksjon)',
    FieldLabelApiKeyPlaceholder: 'Legg til hvis APIM-endepunkt ikke brukes',
    FieldLabelAppId: 'Client ID: create a user_impersonation app with name=openaiwp',
    FieldLabelEndpointBaseUrlForChatHistory: 'Base URL for Chat WebApi (APIM API eller full)',
    FieldLabelEndpointBaseUrlForOpenAi: 'Base URL for GPT-endepunkt (APIM API eller full)',
    FieldLabelEndpointBaseUrlForOpenAi4: 'Base URL for GPT4-endepunkt (APIM API eller full)',
    FieldLabelBing: 'Bing-søk',
    FieldLabelBingApiKey: 'Valgfri api-nøkkel for Bing',
    FieldLabelBingApiKeyPlaceholder: 'Legg til hvis APIM-endepunkt ikke er konfigurert',
    FieldLabelLanguageModels: 'Språkmodeller',
    FieldLabelLocale: 'Lokal for datoer (standard er fi-FI)',
    FieldLabelSharing: 'Aktiver deling',
    FieldLabelStreaming: 'Aktiver strømming',
    FieldLabelFullScreen: 'Aktiver integrasjoner',
    FieldLabelFunctions: 'Aktiver eksterne funksjonsanrop',
    FieldLabelHighlight: 'Kodeutheving',
    FieldLabelHighlightStyles: 'Vis uthevingsstiler',
    FieldLabelDefaultStyle: 'Standard stil',
    FieldLabelSharePointListUrl: 'SharePoint-liste URL (la den stå tom for standard URL)',
    FieldLabelStorageType: 'Lagringstype for chattelogg',
    FieldLabelStorageTypeDatabase: 'Database',
    FieldLabelStorageTypeLocalStorage: 'Lokal lagring',
    FieldLabelStorageTypeSharePoint: 'SharePoint-liste',
    FieldLabelDemoOnly: '(kun demo)',
    FieldLabelPromptAtBottom: 'Vis ledetekstområdet nederst',
    FieldLabelUnlimitedHistoryLength: 'Ubegrenset lengde på chatteloggen (AI-svar i lange chatter kan være mindre nøyaktige)',

    PlaceholderDescription: 'Konfigurer denne webdelen.',
    PlaceholderText: 'Konfigurer webdelen din',

    TextAllResults: 'Alle resultater',
    TextAuthenticationError: 'Autentiseringsfeil (se konsollmeldinger for detaljer)',
    TextCancel: 'Avbryt',
    TextCharacters: 'tegn',
    TextChat: 'ChatGPT',
    TextClose: 'Lukk',
    TextCodeStyle: 'Kode stil',
    TextCollapse: 'Skjul',
    TextCommands: 'kommandoer',
    TextConfigure: 'Konfigurer',
    TextCopy: 'Kopier',
    TextCreate: 'Lag',
    TextCreated: 'Opprettet',
    TextDelete: 'Slett',
    TextDeleteMessage: 'Vil du slette',
    TextDescribeImage: 'Hva er på dette bildet?',
    TextDescribeImages: 'Hva er i disse bildene?',
    TextDemoOnly: '(demo only)',
    TextEdit: 'Rediger',
    TextError: 'Feil oppsto',
    TextExpand: 'Utvid',
    TextExists: 'Finnes',
    TextFormat: 'Rå',
    TextFullScreen: 'Til fullskjerm',
    TextGpt35: 'GPT-3.5',
    TextGpt4: 'GPT-4',
    TextGpt4Turbo: 'GPT-4 Turbo',
    TextHideMySharedChats: 'Skjul chattene mine',
    TextInvalidListUrl: 'Ugyldig liste-URL. Egendefinert liste med samme navn finnes allerede på nettstedet',
    TextListCreated: 'Egendefinert liste er opprettet',
    TextListDoesNotExist: 'Egendefinert liste finnes ikke',
    TextListExists: 'Egendefinert liste eksisterer allerede',
    TextListUpdated: 'Egendefinert liste har blitt oppdatert',
    TextMaxContentLengthExceeded: 'Maksimal lengde for chatlogg tillatt av den valgte språkmodellen er overskredet. Start en ny chat eller velg en annen språkmodell.',
    TextModified: 'Sist endret',
    TextMoreCharactersAllowed: 'mer tillatt',
    TextNewChat: 'Ny chat',
    TextPeoplePicker: 'Folkevelger',
    TextPeoplePickerLoading: 'Laster',
    TextPeoplePickerNoResults: 'Ingen resultater funnet',
    TextPeoplePickerSuggestedContacts: 'Foreslåtte kontakter',
    TextPeoplePickerSuggestedPeople: 'Foreslåtte personer',
    TextPeoplePickerSuggestionsAvailable: 'Folkevelger Forslag tilgjengelig',
    TextPreview: 'Forhåndsvisning, ikke for produksjon',
    TextRecentChats: 'Mine chatter',
    TextRefresh: 'Oppdater',
    TextRemove: 'Fjern',
    TextSave: 'Lagre',
    TextSendMessage: 'Send en melding',
    TextShare: 'Del',
    TextShared: 'Delt',
    TextShareMessage: 'Vil du dele',
    TextSharedChats: 'Delte chatter',
    TextShareWith: 'Spesifikke personer å dele med (hvis du vil begrense tilgangen til denne chatten, maks 15 personer)',
    TextSubmit: 'Send',
    TextSummarizePdf: 'Oppsummer PDF-innhold',
    TextUdeterminedError: 'Ubestemt feil',
    TextUnshare: 'Opphev deling',
    TextUnshareMessage: 'Vil du oppheve deling',
    TextUpdate: 'Oppdater',
    TextUpdated: 'Oppdatert',
    TextUploadImage: 'Last opp',
    TextUploadFiles: 'Last opp filer',
    TextUploadImage: 'Last opp bilder',
    TextUploadImage: 'Last opp PDF',
  };
});
