define([], function () {
  return {
    BasicGroupName: 'Innstillinger',
    FieldLabelApiKey: 'Valgfri api-nøkkel for Azure OpenAI (for feilsøking, ikke for produksjon)',
    FieldLabelApiKeyPlaceholder: 'Legg til hvis APIM-endepunkt ikke brukes',
    FieldLabelAppId: 'Client ID: create a user_impersonation app with name=openaiwp',
    FieldLabelEndpointBaseUrlForChatHistory: 'Base URL for Chat WebApi (APIM API eller full)',
    FieldLabelEndpointBaseUrlForOpenAi: 'Base URL for GPT-endepunkt (APIM API eller full)',
    FieldLabelEndpointBaseUrlForOpenAi4: 'Base URL for GPT4-endepunkt (APIM API eller full)',
    FieldLabelBing: 'Bing-søk',
    FieldLabelBingApiKey: 'Valgfri api-nøkkel for Bing',
    FieldLabelBingApiKeyPlaceholder: 'Legg til hvis APIM-endepunkt ikke er konfigurert',
    FieldLabelEncryption: 'Aktiver lagringskryptering',
    FieldLabelExamples: 'Aktiver eksempler for ledeteksten',
    FieldLabelGoogle: 'Google-søk',
    FieldLabelGoogleApiKey: 'Valgfri nøkkel for Google: key=API_NØKKEL&cx=SØKEMOTORID',
    FieldLabelImages: 'Bildegenerering (Dalle)',
    FieldLabelImagesApim: 'Bildegenerering: konfigurer /dalle (docs)',
    FieldLabelLanguageModels: 'Språkmodeller',
    FieldLabelLocale: 'Lokal for datoer (standard er fi-FI)',
    FieldLabelSharing: 'Aktiver deling',
    FieldLabelStreaming: 'Aktiver strømming',
    FieldLabelFullScreen: 'Aktiver integrasjoner',
    FieldLabelFunctions: 'Aktiver eksterne funksjonsanrop',
    FieldLabelHighlight: 'Kodeutheving',
    FieldLabelHighlightStyles: 'Vis uthevingsstiler',
    FieldLabelDefaultStyle: 'Standard stil',
    FieldLabelSharePointImageLibraryUrl: 'Bildebibliotekets URL (la den stå tom for standard URL)',
    FieldLabelSharePointListUrl: 'SharePoint-liste URL (la den stå tom for standard URL)',
    FieldLabelStorageType: 'Lagringstype for chattelogg',
    FieldLabelStorageTypeDatabase: 'Database',
    FieldLabelStorageTypeLocalStorage: 'Lokal lagring',
    FieldLabelStorageTypeSharePoint: 'SharePoint-liste',
    FieldLabelDemoOnly: '(kun demo)',
    FieldLabelPromptAtBottom: 'Vis ledetekstområdet nederst',
    FieldLabelUnlimitedHistoryLength: 'Ubegrenset lengde på chatteloggen (AI-svar i lange chatter kan være mindre nøyaktige)',
    FieldLabelVision: 'Bildeanalyse (Vision)',
    FieldLabelVisionApim: 'Bildeanalyse: konfigurer /vision (docs)',
    FieldLabelVoiceInput: 'Aktiver stemmeinndata',
    FieldLabelVoiceOutput: 'Aktiver stemmeutgang (tekst til tale)',

    PlaceholderDescription: 'Konfigurer denne webdelen.',
    PlaceholderText: 'Konfigurer webdelen din',

    TextAllResults: 'Alle resultater',
    TextAuthenticationError: 'Autentiseringsfeil (se konsollmeldinger for detaljer)',
    TextCancel: 'Avbryt',
    TextCharacters: 'tegn',
    TextChat: 'ChatGPT',
    TextClose: 'Lukk',
    TextCodeStyle: 'Kode stil',
    TextCollapse: 'Skjul',
    TextCommands: 'resultat',
    TextConfigure: 'Konfigurer',
    TextCopy: 'Kopier',
    TextCreate: 'Lag',
    TextCreated: 'Opprettet',
    TextDelete: 'Slett',
    TextDeleteMessage: 'Vil du slette',
    TextDescribeImage: 'Hva er på dette bildet?',
    TextDescribeImages: 'Hva er i disse bildene?',
    TextDeviceUnavailable: 'Enheten er utilgjengelig',
    TextDemoOnly: '(kun demo)',
    TextEdit: 'Rediger',
    TextError: 'Feil oppsto',
    TextExamples: 'Eksempler',
    TextExists: 'Finnes',
    TextExpand: 'Utvid',
    TextFormat: 'Rå',
    TextFullScreen: 'Til fullskjerm',
    TextGpt35: 'GPT-3.5',
    TextGpt4: 'GPT-4',
    TextGpt4o: 'GPT-4o',
    TextGpt4oMini: 'GPT-4o Mini',
    TextGpt41: 'GPT-4.1',
    TextGpt41Mini: 'GPT-4.1 Mini',
    TextGpt41Nano: 'GPT-4.1 Nano',
    TextGpt4Turbo: 'GPT-4 Turbo',
    TextGpt5: 'GPT-5',
    TextGpt5Chat: 'GPT-5 Chat',
    TextGpt5Mini: 'GPT-5 Mini',
    TextGpt5Nano: 'GPT-5 Nano',
    TextO1Mini: 'O1 Mini',
    TextO1Preview: 'O1 Preview',
    TextO1: 'O1',
    TextO3Mini: 'O3 Mini',
    TextO4Mini: 'O4 Mini',
    TextHideMySharedChats: 'Skjul chattene mine',
    TextInvalidListUrl: 'Ugyldig liste-URL. Liste med samme navn finnes allerede på nettstedet',
    TextLanguage: 'Språk',
    TextListCreated: 'Liste er opprettet',
    TextListDoesNotExist: 'Liste finnes ikke',
    TextListExists: 'Liste eksisterer allerede',
    TextListUpdated: 'Liste har blitt oppdatert',
    TextMaxContentLengthExceeded: 'Maksimal lengde for chatlogg tillatt av den valgte språkmodellen er overskredet. Start en ny chat eller velg en annen språkmodell.',
    TextModified: 'Sist endret',
    TextMoreCharactersAllowed: 'mer tillatt',
    TextNewChat: 'Ny chat',
    TextPeoplePicker: 'Folkevelger',
    TextPeoplePickerLoading: 'Laster',
    TextPeoplePickerNoResults: 'Ingen resultater funnet',
    TextPeoplePickerSuggestedContacts: 'Foreslåtte kontakter',
    TextPeoplePickerSuggestedPeople: 'Foreslåtte personer',
    TextPeoplePickerSuggestionsAvailable: 'Folkevelger Forslag tilgjengelig',
    TextPreview: 'Forhåndsvisning, ikke for produksjon',
    TextRecentChats: 'Mine chatter',
    TextRefresh: 'Oppdater',
    TextRemove: 'Fjern',
    TextSave: 'Lagre',
    TextSendMessage: 'Send en melding',
    TextShare: 'Del',
    TextShared: 'Delt',
    TextShareMessage: 'Vil du dele',
    TextSharedChats: 'Delte chatter',
    TextShareWith: 'Spesifikke personer å dele med (hvis du vil begrense tilgangen til denne chatten, maks 15 personer)',
    TextStop: 'Stopp',
    TextStreamingUnsupported: 'strømmingsalternativet støttes ikke for denne modellen',
    TextSubmit: 'Send',
    TextSummarizePdf: 'Oppsummer PDF-innhold',
    TextUndeterminedError: 'Uventet feil',
    TextUnshare: 'Opphev deling',
    TextUnshareMessage: 'Vil du oppheve deling',
    TextUpdate: 'Oppdater',
    TextUpdated: 'Oppdatert',
    TextUpload: 'Last opp',
    TextUploadFiles: 'Last opp filer',
    TextUploadImage: 'Last opp bilder',
    TextUploadPdf: 'Last opp PDF',
    TextVoiceInput: 'Stemmeinndata',
    TextVoiceOutput: 'Les opp',
  };
});
