declare interface IAzureOpenAiChatWebPartStrings {
  BasicGroupName: string;
  FieldLabelApiKey: string;
  FieldLabelAppId: string;
  FieldLabelEndpointBaseUrlForChatHistory: string;
  FieldLabelEndpointBaseUrlForOpenAi: string;
  FieldLabelEndpointBaseUrlForOpenAi4: string;
  FieldLabelLanguageModels: string;
  FieldLabelLocale: string;
  FieldLabelSharing: string;
  FieldLabelStreaming: string;
  FieldLabelFullScreen: string;
  FieldLabelFunctions: string;
  FieldLabelHighlight: string;
  FieldLabelHighlightStyles: string;
  FieldLabelDefaultStyle: string;
  FieldLabelSharePointListUrl: string;
  FieldLabelStorageType: string;
  FieldLabelStorageTypeDatabase: string;
  FieldLabelStorageTypeLocalStorage: string;
  FieldLabelStorageTypeSharePoint: string;
  FieldLabelDemoOnly: string;
  FieldLabelPromptAtBottom: string;
  FieldLabelUnlimitedHistoryLength: string;

  PlaceholderDescription: string;
  PlaceholderText: string;

  TextAllResults: string;
  TextAuthenticationError: string;
  TextCancel: string;
  TextCharacters: string;
  TextChat: string;
  TextClose: string;
  TextCodeStyle: string;
  TextCollapse: string;
  TextCommands: string;
  TextConfigure: string;
  TextCopy: string;
  TextCreate: string;
  TextCreated: string;
  TextDelete: string;
  TextDeleteMessage: string;
  TextDescribeImage: string;
  TextDescribeImages: string;
  TextEdit: string;
  TextError: string;
  TextExists: string;
  TextExpand: string;
  TextFormat: string;
  TextFullScreen: string;
  TextGpt35: string;
  TextGpt4: string;
  TextHideMySharedChats: string;
  TextInvalidListUrl: string;
  TextListCreated: string;
  TextListDoesNotExist: string;
  TextListExists: string;
  TextListUpdated: string;
  TextMaxContentLengthExceeded: string;
  TextModified: string;
  TextMoreCharactersAllowed: string;
  TextNewChat: string;
  TextPeoplePicker: string;
  TextPeoplePickerLoading: string;
  TextPeoplePickerNoResults: string;
  TextPeoplePickerSuggestedContacts: string;
  TextPeoplePickerSuggestedPeople: string;
  TextPeoplePickerSuggestionsAvailable: string;
  TextRecentChats: string;
  TextRefresh: string;
  TextRemove: string;
  TextSave: string;
  TextSendMessage: string;
  TextShare: string;
  TextShared: string;
  TextShareMessage: string;
  TextSharedChats: string;
  TextShareWith: string;
  TextSubmit: string;
  TextSummarizePdf: string;
  TextUndeterminedError: string;
  TextUnshare: string;
  TextUnshareMessage: string;
  TextUpdate: string;
  TextUpdated: string;
  TextUpload: string;
  TextUploadFiles: string;
  TextUploadImage: string;
  TextUploadPdf: string;
}

declare module 'AzureOpenAiChatWebPartStrings' {
  const strings: IAzureOpenAiChatWebPartStrings;
  export = strings;
}
